### ISSUE TITLE
Make a list of your skills and interests in accordance with the Phase 2 Specification

### ISSUE THREAD

**Issue by chloehumphrey** [cs-450-project/se-phase2#3]
Your lists can be posted here as comments!  We want to assign feature specific roles for this second phase of the project, so the more detail you go into here, the better suited you'll be for your role. Look through the [Project Specification](https://purdue0-my.sharepoint.com/:w:/r/personal/humphr30_purdue_edu/_layouts/15/Doc.aspx?sourcedoc=%7B29D46561-AE24-4F8E-9FEC-3C54D591F852%7D&file=Phase2-Project-Specification.docx&action=default&mobileredirect=true) for context as to possible roles/features you could handle.

**Comment by chloehumphrey** [comment]
#### Chloe's List
- I previously worked for a cybersecurity company, and I specialized in web application vulnerabilities. I have a lot of familiarity with OWASP Top 10 and threat assessment.
- I prefer working on the backend. I haven't worked with AWS much, but I think it would be a good learning experience for me. 
- Software testing is my guilty pleasure.
- In addition to project manager and design duties, I'd probably be best suited to fill the "DevSecOps" role to fulfil the AWS, security, and backend API requirements of the project. This could involve setting up the API to work with the project, accessing vulnerabilities, and configuring AWS from a security standpoint. This fits well with the QA/testing duties as well.

**Comment by YaminiKrubha** [comment]
1. I prefer working with the backend development. I enjoy working on system architecture.
2. Would love to explore frontend and cybersecurity
3. I don't have experience with AWS but can learn!

**Comment by adhabib** [comment]
- I have more of a preference for front end development but I'm open to learning more on working on back end
- I have previously worked on an iOS app that was created in Unity 3D and scripted in C#
- I do not have experience with AWS but I'm sure it would be valuable to learn how to work with it

**Comment by Ca3de** [comment]
I have a strong preference for backend development, though I'm still learning the intricacies of networking. My background includes working at a healthcare company, not in a tech role, but as a receptionist. Currently, I work at Amazon as an Inventory Management Associate. I also have experience in game development, both 3D and 2D, using Unity and Unreal Engine. I'm particularly confident in my C# skills, as I primarily use it in Unity, while I rely on Blueprints for Unreal. Although I’ve attempted to explore AWS, my knowledge there is quite limited, so I’m essentially a beginner in that area.
